<?xml version="1.0" encoding="UTF-8"?>
<testrun name="TestBuyerAction" project="esiea_bid" tests="16" started="16" failures="1" errors="0" ignored="0">
  <testsuite name="test.TestBuyerAction" time="0.004">
    <testcase name="testDeleteAlarmSucess" classname="test.TestBuyerAction" time="0.0">
      <failure>java.lang.AssertionError: expected:&lt;0&gt; but was:&lt;1&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at test.TestBuyerAction.testDeleteAlarmSucess(TestBuyerAction.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
    <testcase name="testCreateAlarmSuccess" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBuyerOfferEmptyList" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBidSuccessOffer" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBuyerOfferSuccess" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testCreateAlarmAlreadyExist" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBidSuccess" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDeleteNonExistingAlarm" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testdoOfferByTheSeller" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBidBadUserForOffer" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBuyerOfferBadUser" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testDisplayBidBadStateCanceled" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testdoOfferBadPrice" classname="test.TestBuyerAction" time="0.001"/>
    <testcase name="testdoOfferBidNotPublished" classname="test.TestBuyerAction" time="0.0"/>
    <testcase name="testdoOfferSucess" classname="test.TestBuyerAction" time="0.001"/>
    <testcase name="testDisplayBidBadStateCreated" classname="test.TestBuyerAction" time="0.001"/>
  </testsuite>
</testrun>
